QSL_RCVD_ENUMERATION = {'': [''],
                        'Yes': ['Y'],
                        'No': ['N'],
                        'Requested': ['R'],
                        'ignore or invalid': ['I']}

QSL_SENT_ENUMERATION = {'': [''],
                        'Yes': ['Y'],
                        'No': ['N'],
                        'Requested': ['R'],
                        'Queued': ['Q'],
                        'ignore or invalid': ['I']}

MODES_WITH_SUBMODE = {'': [''],
                      'AM': [''],
                      'ARDOP': [''],
                      'ATV': [''],
                      'C4FM': [''],
                      'CHIP': ['', 'CHIP64', 'CHIP128'],
                      'CLO': [''],
                      'CONTESTI': [''],
                      'CW': ['', 'PCW'],
                      'DIGITALVOICE': [''],
                      'DOMINO': [
                          '', 'DOM-M', 'DOM4', 'DOM5', 'DOM8', 'DOM11', 'DOM16', 'DOM22', 'DOM44', 'DOM88', 'DOMINOEX',
                          'DOMINOF'],
                      'DSTAR': [''],
                      'FAX': [''],
                      'FM': [''],
                      'FSK441': [''],
                      'FT8': [''],
                      'HELL': ['', 'FMHELL', 'FSKHELL', 'HELL80', 'HELLX5', 'HELLX9', 'HFSK', 'PSKHELL', 'SLOWHELL'],
                      'ISCAT': ['', 'ISCAT-A', 'ISCAT-B'],
                      'JT4': ['', 'JT4A', 'JT4B', 'JT4C', 'JT4D', 'JT4E', 'JT4F', 'JT4G'],
                      'JT6M': [''],
                      'JT9': [
                          '', 'JT9-1', 'JT9-2', 'JT9-5', 'JT9-10', 'JT9-30', 'JT9A', 'JT9B', 'JT9C', 'JT9D', 'JT9E',
                          'JT9E FAST', 'JT9F', 'JT9F FAST', 'JT9G', 'JT9G FAST', 'JT9H', 'JT9H FAST'],
                      'JT44': [''],
                      'JT65': ['', 'JT65A', 'JT65B', 'JT65B2', 'JT65C', 'JT65C2'],
                      'MFSK': [
                          '', 'FSQCALL', 'FST4', 'FST4W', 'FT4', 'JS8', 'JTMS', 'MFSK4', 'MFSK8', 'MFSK11', 'MFSK16',
                          'MFSK22', 'MFSK31', 'MFSK32', 'MFSK64', 'MFSK64L', 'MFSK128', 'MFSK128L', 'Q65'],
                      'MSK144': [''],
                      'MT63': [''],
                      'OLIVIA': ['', 'OLIVIA 4/125', 'OLIVIA 4/250', 'OLIVIA 8/250', 'OLIVIA 8/500', 'OLIVIA 16/500',
                                 'OLIVIA 16/1000', 'OLIVIA 32/1000'],
                      'OPERA': ['', 'OPERA-BEACON', 'OPERA-QSO'],
                      'PAC': ['', 'PAC2', 'PAC3', 'PAC4'],
                      'PAX': ['', 'PAX2'],
                      'PKT': [''],
                      'PSK': ['', '8PSK125', '8PSK125F', '8PSK125FL', '8PSK250', '8PSK250F', '8PSK250FL', '8PSK500',
                              '8PSK500F',
                              '8PSK1000', '8PSK1000F', '8PSK1200F', 'FSK31', 'PSK10', 'PSK31', 'PSK63', 'PSK63F',
                              'PSK63RC4',
                              'PSK63RC5', 'PSK63RC10', 'PSK63RC20', 'PSK63RC32', 'PSK125', 'PSK125C12', 'PSK125R',
                              'PSK125RC10',
                              'PSK125RC12', 'PSK125RC16', 'PSK125RC4', 'PSK125RC5', 'PSK250', 'PSK250C6', 'PSK250R',
                              'PSK250RC2',
                              'PSK250RC3', 'PSK250RC5', 'PSK250RC6', 'PSK250RC7', 'PSK500', 'PSK500C2', 'PSK500C4',
                              'PSK500R',
                              'PSK500RC2', 'PSK500RC3', 'PSK500RC4', 'PSK800C2', 'PSK800RC2', 'PSK1000', 'PSK1000C2',
                              'PSK1000R',
                              'PSK1000RC2', 'PSKAM10', 'PSKAM31', 'PSKAM50', 'PSKFEC31', 'QPSK31', 'QPSK63', 'QPSK125',
                              'QPSK250',
                              'QPSK500', 'SIM31'],
                      'PSK2K': [''],
                      'Q15': [''],
                      'QRA64': ['', 'QRA64A', 'QRA64B', 'QRA64C', 'QRA64D', 'QRA64E'],
                      'ROS': ['', 'ROS-EME', 'ROS-HF', 'ROS-MF'],
                      'RTTY': ['', 'ASCI'],
                      'RTTYM': [''],
                      'SSB': ['', 'LSB', 'USB'],
                      'SSTV': [''],
                      'T10': [''],
                      'THOR': [
                          '', 'THOR-M', 'THOR4', 'THOR5', 'THOR8', 'THOR11', 'THOR16', 'THOR22', 'THOR25X4',
                          'THOR50X1',
                          'THOR50X2', 'THOR100'],
                      'THRB': ['', 'THRBX', 'THRBX1', 'THRBX2', 'THRBX4', 'THROB1', 'THROB2', 'THROB4'],
                      'TOR': ['', 'AMTORFEC', 'GTOR', 'NAVTEX', 'SITORB'],
                      'V4': [''],
                      'VOI': [''],
                      'WINMOR': [''],
                      'WSPR': ['']}

CANTONS = {'': [''],
           'AG': ['Aargau'], 'AR': ['Appenzell Ausserrhoden'], 'AI': ['Appenzell Innerrhoden'],
           'BL': ['Basel Landschaft'], 'BS': ['Basel Stadt'], 'BE': ['Bern'], 'FR': ['Freiburg / Fribourg'],
           'GE': ['Genf / Genève'], 'GL': ['Glarus'], 'GR': ['Graubuenden / Grisons'], 'JU': ['Jura'],
           'LU': ['Luzern'], 'NE': ['Neuenburg / Neuchâtel'], 'NW': ['Nidwalden'], 'OW': ['Obwalden'],
           'SH': ['Schaffhausen'], 'SZ': ['Schwyz'], 'SO': ['Solothurn'], 'SG': ['St. Gallen'],
           'TI': ['Tessin / Ticino'], 'TG': ['Thurgau'], 'UR': ['Uri'], 'VD': ['Waadt / Vaud'],
           'VS': ['Wallis / Valais'], 'ZH': ['Zuerich'], 'ZG': ['Zug']}

BAND_WITH_FREQUENCY = {'': [0, 0],
                       '2190m': [.1357, .1378],
                       '630m': [.472, .479],
                       '560m': [.501, .504],
                       '160m': [1.8, 2.0],
                       '80m': [3.5, 4.0],
                       '60m': [5.06, 5.45],
                       '40m': [7.0, 7.3],
                       '30m': [10.1, 10.15],
                       '20m': [14.0, 14.35],
                       '17m': [18.068, 18.168],
                       '15m': [21.0, 21.45],
                       '12m': [24.890, 24.99],
                       '10m': [28.0, 29.7],
                       '8m': [40, 45],
                       '6m': [50, 54],
                       '5m': [54.000001, 69.9],
                       '4m': [70, 71],
                       '2m': [144, 148],
                       '1.25m': [222, 225],
                       '70cm': [420, 450],
                       '33cm': [902, 928],
                       '23cm': [1240, 1300],
                       '13cm': [2300, 2450],
                       '9cm': [3300, 3500],
                       '6cm': [5650, 5925],
                       '3cm': [10000, 10500],
                       '1.25cm': [24000, 24250],
                       '6mm': [47000, 47200],
                       '4mm': [75500, 81000],
                       '2.5mm': [119980, 123000],
                       '2mm': [134000, 149000],
                       '1mm': [241000, 250000]}

DXCC_CODE_WITH_NAME = {'0': ['None [the contacted station is known to not be within a DXCC entity]'],
                       '1': ['CANADA'], '2': ['ABU AIL IS.', 'Y'], '3': ['AFGHANISTAN'],
                       '4': ['AGALEGA & ST. BRANDON IS.'], '5': ['ALAND IS.'], '6': ['ALASKA'],
                       '7': ['ALBANIA'], '8': ['ALDABRA', 'Y'], '9': ['AMERICAN SAMOA'],
                       '10': ['AMSTERDAM & ST. PAUL IS.'], '11': ['ANDAMAN & NICOBAR IS.'],
                       '12': ['ANGUILLA'], '13': ['ANTARCTICA'], '14': ['ARMENIA'],
                       '15': ['ASIATIC RUSSIA'], '16': ['NEW ZEALAND SUBANTARCTIC ISLANDS'],
                       '17': ['AVES I.'], '18': ['AZERBAIJAN'], '19': ['BAJO NUEVO', 'Y'],
                       '20': ['BAKER & HOWLAND IS.'], '21': ['BALEARIC IS.'], '22': ['PALAU'],
                       '23': ['BLENHEIM REEF', 'Y'], '24': ['BOUVET'], '25': ['BRITISH NORTH BORNEO', 'Y'],
                       '26': ['BRITISH SOMALILAND', 'Y'], '27': ['BELARUS'], '28': ['CANAL ZONE', 'Y'],
                       '29': ['CANARY IS.'], '30': ['CELEBE & MOLUCCA IS.', 'Y'],
                       '31': ['C. KIRIBATI [BRITISH PHOENIX IS.]'], '32': ['CEUTA & MELILLA'],
                       '33': ['CHAGOS IS.'], '34': ['CHATHAM IS.'], '35': ['CHRISTMAS I.'],
                       '36': ['CLIPPERTON I.'], '37': ['COCOS I.'], '38': ['COCOS [KEELING] IS.'],
                       '39': ['COMOROS', 'Y'], '40': ['CRETE'], '41': ['CROZET I.'], '42': ['DAMAO, DIU', 'Y'],
                       '43': ['DESECHEO I.'], '44': ['DESROCHES', 'Y'], '45': ['DODECANESE'],
                       '46': ['EAST MALAYSIA'], '47': ['EASTER I.'], '48': ['E. KIRIBATI [LINE IS.]'],
                       '49': ['EQUATORIAL GUINEA'], '50': ['MEXICO'], '51': ['ERITREA'],
                       '52': ['ESTONIA'], '53': ['ETHIOPIA'], '54': ['EUROPEAN RUSSIA'],
                       '55': ['FARQUHAR', 'Y'], '56': ['FERNANDO DE NORONHA'],
                       '57': ['FRENCH EQUATORIAL AFRICA', 'Y'], '58': ['FRENCH INDO-CHINA', 'Y'],
                       '59': ['FRENCH WEST AFRICA', 'Y'], '60': ['BAHAMAS'], '61': ['FRANZ JOSEF LAND'],
                       '62': ['BARBADOS'], '63': ['FRENCH GUIANA'], '64': ['BERMUDA'],
                       '65': ['BRITISH VIRGIN IS.'], '66': ['BELIZE'], '67': ['FRENCH INDIA', 'Y'],
                       '68': ['KUWAIT/SAUDI ARABIA NEUTRAL ZONE', 'Y'], '69': ['CAYMAN IS.'], '70': ['CUBA'],
                       '71': ['GALAPAGOS IS.'], '72': ['DOMINICAN REPUBLIC'], '74': ['EL SALVADOR'],
                       '75': ['GEORGIA'], '76': ['GUATEMALA'], '77': ['GRENADA'], '78': ['HAITI'],
                       '79': ['GUADELOUPE'], '80': ['HONDURAS'], '81': ['GERMANY', 'Y'], '82': ['JAMAICA'],
                       '84': ['MARTINIQUE'], '85': ['BONAIRE, CURACAO', 'Y'], '86': ['NICARAGUA'],
                       '88': ['PANAMA'], '89': ['TURKS & CAICOS IS.'], '90': ['TRINIDAD & TOBAGO'],
                       '91': ['ARUBA'], '93': ['GEYSER REEF', 'Y'], '94': ['ANTIGUA & BARBUDA'],
                       '95': ['DOMINICA'], '96': ['MONTSERRAT'], '97': ['ST. LUCIA'],
                       '98': ['ST. VINCENT'], '99': ['GLORIOSO IS.'], '100': ['ARGENTINA'],
                       '101': ['GOA', 'Y'], '102': ['GOLD COAST, TOGOLAND', 'Y'], '103': ['GUAM'],
                       '104': ['BOLIVIA'], '105': ['GUANTANAMO BAY'], '106': ['GUERNSEY'],
                       '107': ['GUINEA'], '108': ['BRAZIL'], '109': ['GUINEA-BISSAU'],
                       '110': ['HAWAII'], '111': ['HEARD I.'], '112': ['CHILE'], '113': ['IFNI', 'Y'],
                       '114': ['ISLE OF MAN'], '115': ['ITALIAN SOMALILAND', 'Y'], '116': ['COLOMBIA'],
                       '117': ['ITU HQ'], '118': ['JAN MAYEN'], '119': ['JAVA', 'Y'], '120': ['ECUADOR'],
                       '122': ['JERSEY'], '123': ['JOHNSTON I.'], '124': ['JUAN DE NOVA, EUROPA'],
                       '125': ['JUAN FERNANDEZ IS.'], '126': ['KALININGRAD'], '127': ['KAMARAN IS.', 'Y'],
                       '128': ['KARELO-FINNISH REPUBLIC', 'Y'], '129': ['GUYANA'], '130': ['KAZAKHSTAN'],
                       '131': ['KERGUELEN IS.'], '132': ['PARAGUAY'], '133': ['KERMADEC IS.'],
                       '134': ['KINGMAN REEF', 'Y'], '135': ['KYRGYZSTAN'], '136': ['PERU'],
                       '137': ['REPUBLIC OF KOREA'], '138': ['KURE I.'], '139': ['KURIA MURIA I.', 'Y'],
                       '140': ['SURINAME'], '141': ['FALKLAND IS.'], '142': ['LAKSHADWEEP IS.'],
                       '143': ['LAOS'], '144': ['URUGUAY'], '145': ['LATVIA'], '146': ['LITHUANIA'],
                       '147': ['LORD HOWE I.'], '148': ['VENEZUELA'], '149': ['AZORES'],
                       '150': ['AUSTRALIA'], '151': ['MALYJ VYSOTSKIJ I.', 'Y'], '152': ['MACAO'],
                       '153': ['MACQUARIE I.'], '154': ['YEMEN ARAB REPUBLIC', 'Y'], '155': ['MALAYA', 'Y'],
                       '157': ['NAURU'], '158': ['VANUATU'], '159': ['MALDIVES'], '160': ['TONGA'],
                       '161': ['MALPELO I.'], '162': ['NEW CALEDONIA'], '163': ['PAPUA NEW GUINEA'],
                       '164': ['MANCHURIA', 'Y'], '165': ['MAURITIUS'], '166': ['MARIANA IS.'],
                       '167': ['MARKET REEF'], '168': ['MARSHALL IS.'], '169': ['MAYOTTE'],
                       '170': ['NEW ZEALAND'], '171': ['MELLISH REEF'], '172': ['PITCAIRN I.'],
                       '173': ['MICRONESIA'], '174': ['MIDWAY I.'], '175': ['FRENCH POLYNESIA'],
                       '176': ['FIJI'], '177': ['MINAMI TORISHIMA'], '178': ['MINERVA REEF', 'Y'],
                       '179': ['MOLDOVA'], '180': ['MOUNT ATHOS'], '181': ['MOZAMBIQUE'],
                       '182': ['NAVASSA I.'], '183': ['NETHERLANDS BORNEO', 'Y'],
                       '184': ['NETHERLANDS NEW GUINEA', 'Y'], '185': ['SOLOMON IS.'],
                       '186': ['NEWFOUNDLAND, LABRADOR', 'Y'], '187': ['NIGER'], '188': ['NIUE'],
                       '189': ['NORFOLK I.'], '190': ['SAMOA'], '191': ['NORTH COOK IS.'],
                       '192': ['OGASAWARA'], '193': ['OKINAWA [RYUKYU IS.]', 'Y'], '194': ['OKINO TORI-SHIMA', 'Y'],
                       '195': ['ANNOBON I.'], '196': ['PALESTINE', 'Y'], '197': ['PALMYRA & JARVIS IS.'],
                       '198': ['PAPUA TERRITORY', 'Y'], '199': ['PETER 1 I.'], '200': ['PORTUGUESE TIMOR', 'Y'],
                       '201': ['PRINCE EDWARD & MARION IS.'], '202': ['PUERTO RICO'], '203': ['ANDORRA'],
                       '204': ['REVILLAGIGEDO'], '205': ['ASCENSION I.'], '206': ['AUSTRIA'],
                       '207': ['RODRIGUEZ I.'], '208': ['RUANDA-URUNDI', 'Y'], '209': ['BELGIUM'],
                       '210': ['SAAR', 'Y'], '211': ['SABLE I.'], '212': ['BULGARIA'],
                       '213': ['SAINT MARTIN'], '214': ['CORSICA'], '215': ['CYPRUS'],
                       '216': ['SAN ANDRES & PROVIDENCIA'], '217': ['SAN FELIX & SAN AMBROSIO'],
                       '218': ['CZECHOSLOVAKIA', 'Y'], '219': ['SAO TOME & PRINCIPE'], '220': ['SARAWAK', 'Y'],
                       '221': ['DENMARK'], '222': ['FAROE IS.'], '223': ['ENGLAND'], '224': ['FINLAND'],
                       '225': ['SARDINIA'], '226': ['SAUDI ARABIA/IRAQ NEUTRAL ZONE', 'Y'], '227': ['FRANCE'],
                       '228': ['SERRANA BANK & RONCADOR CAY', 'Y'], '229': ['GERMAN DEMOCRATIC REPUBLIC', 'Y'],
                       '230': ['FEDERAL REPUBLIC OF GERMANY'], '231': ['SIKKIM', 'Y'], '232': ['SOMALIA'],
                       '233': ['GIBRALTAR'], '234': ['SOUTH COOK IS.'], '235': ['SOUTH GEORGIA I.'],
                       '236': ['GREECE'], '237': ['GREENLAND'], '238': ['SOUTH ORKNEY IS.'],
                       '239': ['HUNGARY'], '240': ['SOUTH SANDWICH IS.'], '241': ['SOUTH SHETLAND IS.'],
                       '242': ['ICELAND'], '243': ["PEOPLE'S DEMOCRATIC REP. OF YEMEN", 'Y'],
                       '244': ['SOUTHERN SUDAN', 'Y'], '245': ['IRELAND'],
                       '246': ['SOVEREIGN MILITARY ORDER OF MALTA'], '247': ['SPRATLY IS.'],
                       '248': ['ITALY'], '249': ['ST. KITTS & NEVIS'], '250': ['ST. HELENA'],
                       '251': ['LIECHTENSTEIN'], '252': ['ST. PAUL I.'],
                       '253': ['ST. PETER & ST. PAUL ROCKS'], '254': ['LUXEMBOURG'],
                       '255': ['ST. MAARTEN, SABA, ST. EUSTATIUS', 'Y'], '256': ['MADEIRA IS.'],
                       '257': ['MALTA'], '258': ['SUMATRA', 'Y'], '259': ['SVALBARD'], '260': ['MONACO'],
                       '261': ['SWAN IS.', 'Y'], '262': ['TAJIKISTAN'], '263': ['NETHERLANDS'],
                       '264': ['TANGIER', 'Y'], '265': ['NORTHERN IRELAND'], '266': ['NORWAY'],
                       '267': ['TERRITORY OF NEW GUINEA', 'Y'], '268': ['TIBET', 'Y'], '269': ['POLAND'],
                       '270': ['TOKELAU IS.'], '271': ['TRIESTE', 'Y'], '272': ['PORTUGAL'],
                       '273': ['TRINDADE & MARTIM VAZ IS.'], '274': ['TRISTAN DA CUNHA & GOUGH I.'],
                       '275': ['ROMANIA'], '276': ['TROMELIN I.'], '277': ['ST. PIERRE & MIQUELON'],
                       '278': ['SAN MARINO'], '279': ['SCOTLAND'], '280': ['TURKMENISTAN'],
                       '281': ['SPAIN'], '282': ['TUVALU'], '283': ['UK SOVEREIGN BASE AREAS ON CYPRUS'],
                       '284': ['SWEDEN'], '285': ['VIRGIN IS.'], '286': ['UGANDA'],
                       '287': ['SWITZERLAND'], '288': ['UKRAINE'], '289': ['UNITED NATIONS HQ'],
                       '291': ['UNITED STATES OF AMERICA'], '292': ['UZBEKISTAN'], '293': ['VIET NAM'],
                       '294': ['WALES'], '295': ['VATICAN'], '296': ['SERBIA'], '297': ['WAKE I.'],
                       '298': ['WALLIS & FUTUNA IS.'], '299': ['WEST MALAYSIA'],
                       '301': ['W. KIRIBATI [GILBERT IS. ]'], '302': ['WESTERN SAHARA'],
                       '303': ['WILLIS I.'], '304': ['BAHRAIN'], '305': ['BANGLADESH'],
                       '306': ['BHUTAN'], '307': ['ZANZIBAR', 'Y'], '308': ['COSTA RICA'],
                       '309': ['MYANMAR'], '312': ['CAMBODIA'], '315': ['SRI LANKA'], '318': ['CHINA'],
                       '321': ['HONG KONG'], '324': ['INDIA'], '327': ['INDONESIA'], '330': ['IRAN'],
                       '333': ['IRAQ'], '336': ['ISRAEL'], '339': ['JAPAN'], '342': ['JORDAN'],
                       '344': ["DEMOCRATIC PEOPLE'S REP. OF KOREA"], '345': ['BRUNEI DARUSSALAM'],
                       '348': ['KUWAIT'], '354': ['LEBANON'], '363': ['MONGOLIA'], '369': ['NEPAL'],
                       '370': ['OMAN'], '372': ['PAKISTAN'], '375': ['PHILIPPINES'], '376': ['QATAR'],
                       '378': ['SAUDI ARABIA'], '379': ['SEYCHELLES'], '381': ['SINGAPORE'],
                       '382': ['DJIBOUTI'], '384': ['SYRIA'], '386': ['TAIWAN'], '387': ['THAILAND'],
                       '390': ['TURKEY'], '391': ['UNITED ARAB EMIRATES'], '400': ['ALGERIA'],
                       '401': ['ANGOLA'], '402': ['BOTSWANA'], '404': ['BURUNDI'], '406': ['CAMEROON'],
                       '408': ['CENTRAL AFRICA'], '409': ['CAPE VERDE'], '410': ['CHAD'],
                       '411': ['COMOROS'], '412': ['REPUBLIC OF THE CONGO'],
                       '414': ['DEMOCRATIC REPUBLIC OF THE CONGO'], '416': ['BENIN'], '420': ['GABON'],
                       '422': ['THE GAMBIA'], '424': ['GHANA'], '428': ["COTE D'IVOIRE"],
                       '430': ['KENYA'], '432': ['LESOTHO'], '434': ['LIBERIA'], '436': ['LIBYA'],
                       '438': ['MADAGASCAR'], '440': ['MALAWI'], '442': ['MALI'], '444': ['MAURITANIA'],
                       '446': ['MOROCCO'], '450': ['NIGERIA'], '452': ['ZIMBABWE'],
                       '453': ['REUNION I.'], '454': ['RWANDA'], '456': ['SENEGAL'],
                       '458': ['SIERRA LEONE'], '460': ['ROTUMA I.'], '462': ['SOUTH AFRICA'],
                       '464': ['NAMIBIA'], '466': ['SUDAN'], '468': ['SWAZILAND'], '470': ['TANZANIA'],
                       '474': ['TUNISIA'], '478': ['EGYPT'], '480': ['BURKINA FASO'], '482': ['ZAMBIA'],
                       '483': ['TOGO'], '488': ['WALVIS BAY', 'Y'], '489': ['CONWAY REEF'],
                       '490': ['BANABA I. [OCEAN I.]'], '492': ['YEMEN'], '493': ['PENGUIN IS.', 'Y'],
                       '497': ['CROATIA'], '499': ['SLOVENIA'], '501': ['BOSNIA-HERZEGOVINA'],
                       '502': ['MACEDONIA'], '503': ['CZECH REPUBLIC'], '504': ['SLOVAK REPUBLIC'],
                       '505': ['PRATAS I.'], '506': ['SCARBOROUGH REEF'], '507': ['TEMOTU PROVINCE'],
                       '508': ['AUSTRAL I.'], '509': ['MARQUESAS IS.'], '510': ['PALESTINE'],
                       '511': ['TIMOR-LESTE'], '512': ['CHESTERFIELD IS.'], '513': ['DUCIE I.'],
                       '514': ['MONTENEGRO'], '515': ['SWAINS I.'], '516': ['SAINT BARTHELEMY'],
                       '517': ['CURACAO'], '518': ['ST MAARTEN'], '519': ['SABA & ST. EUSTATIUS'],
                       '520': ['BONAIRE'], '521': ['SOUTH SUDAN [REPUBLIC OF]'],
                       '522': ['REPUBLIC OF KOSOVO']}

ALL_ADIF_FIELDS = [
    'ADDRESS',
    'ADDRESS_INTL',
    'AGE',
    'A_INDEX',
    'ANT_AZ',
    'ANT_EL',
    'ANT_PATH',
    'ARRL_SECT',
    'AWARD_GRANTED',
    'AWARD_SUBMITTED',
    'BAND',
    'BAND_RX',
    'CALL',
    'CHECK',
    'CLASS',
    'CLUBLOG_QSO_UPLOAD_DATE',
    'CLUBLOG_QSO_UPLOAD_STATUS',
    'CNTY',
    'COMMENT',
    'COMMENT_INTL',
    'CONT',
    'CONTACTED_OP',
    'CONTEST_ID',
    'COUNTRY',
    'COUNTRY_INTL',
    'CQZ',
    'CREDIT_SUBMITTED',
    'CREDIT_GRANTED',
    'DARC_DOK',
    'DISTANCE',
    'DXCC',
    'EMAIL',
    'EQ_CALL',
    'EQSL_QSLRDATE',
    'EQSL_QSLSDATE',
    'EQSL_QSL_RCVD',
    'EQSL_QSL_SENT',
    'FISTS',
    'FISTS_CC',
    'FORCE_INIT',
    'FREQ',
    'FREQ_RX',
    'GRIDSQUARE',
    'GUEST_OP',
    'HRDLOG_QSO_UPLOAD_DATE',
    'HRDLOG_QSO_UPLOAD_STATUS',
    'IOTA',
    'IOTA_ISLAND_ID',
    'ITUZ',
    'K_INDEX',
    'LAT',
    'LON',
    'LOTW_QSLRDATE',
    'LOTW_QSLSDATE',
    'LOTW_QSL_RCVD',
    'LOTW_QSL_SENT',
    'MAX_BURSTS',
    'MODE',
    'MS_SHOWER',
    'MY_ANTENNA',
    'MY_ANTENNA_INTL',
    'MY_CITY',
    'MY_CITY_INTL',
    'MY_CNTY',
    'MY_COUNTRY',
    'MY_COUNTRY_INTL',
    'MY_CQ_ZONE',
    'MY_DXCC',
    'MY_FISTS',
    'MY_GRIDSQUARE',
    'MY_IOTA',
    'MY_IOTA_ISLAND_ID',
    'MY_ITU_ZONE',
    'MY_LAT',
    'MY_LON',
    'MY_NAME',
    'MY_NAME_INTL',
    'MY_POSTAL_CODE',
    'MY_POSTAL_CODE_INTL',
    'MY_RIG',
    'MY_RIG_INTL',
    'MY_SIG',
    'MY_SIG_INTL',
    'MY_SIG_INFO',
    'MY_SIG_INFO_INTL',
    'MY_SOTA_REF',
    'MY_STATE',
    'MY_STREET',
    'MY_STREET_INTL',
    'MY_USACA_COUNTIES',
    'MY_VUCC_GRIDS',
    'NAME',
    'NAME_INTL',
    'NOTES',
    'NOTES_INTL',
    'NR_BURSTS',
    'NR_PINGS',
    'OPERATOR',
    'OWNER_CALLSIGN',
    'PFX',
    'PRECEDENCE',
    'PROP_MODE',
    'PUBLIC_KEY',
    'QRZCOM_QSO_UPLOAD_DATE',
    'QRZCOM_QSO_UPLOAD_STATUS',
    'QSLMSG',
    'QSLMSG_INTL',
    'QSLRDATE',
    'QSLSDATE',
    'QSL_RCVD',
    'QSL_RCVD_VIA',
    'QSL_SENT',
    'QSL_SENT_VIA',
    'QSL_VIA',
    'QSO_COMPLETE',
    'QSO_DATE',
    'QSO_DATE_OFF',
    'QSO_RANDOM',
    'QTH',
    'QTH_INTL',
    'REGION',
    'RIG',
    'RIG_INTL',
    'RST_RCVD',
    'RST_SENT',
    'RX_PWR',
    'SAT_MODE',
    'SAT_NAME',
    'SFI',
    'SIG',
    'SIG_INTL',
    'SIG_INFO',
    'SIG_INFO_INTL',
    'SILENT_KEY',
    'SKCC',
    'SOTA_REF',
    'SRX',
    'SRX_STRING',
    'STATE',
    'STATION_CALLSIGN',
    'STX',
    'STX_STRING',
    'SUBMODE',
    'SWL',
    'TEN_TEN',
    'TIME_OFF',
    'TIME_ON',
    'TX_PWR',
    'UKSMG',
    'USACA_COUNTIES',
    'VE_PROV',
    'VUCC_GRIDS',
    'WEB']
